"""add_timestamps_to_fibonacci_state

Revision ID: 34e80ffdd9cf
Revises: 78ad681e813c
Create Date: 2025-09-04 17:03:18.531563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e80ffdd9cf'
down_revision: Union[str, Sequence[str], None] = '78ad681e813c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fibonacci_state', sa.Column('high_point_timestamp', sa.DateTime(), nullable=True))
    op.add_column('fibonacci_state', sa.Column('low_point_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fibonacci_state', 'low_point_timestamp')
    op.drop_column('fibonacci_state', 'high_point_timestamp')
    # ### end Alembic commands ###
