"""replace_after_chart_file_id_with_jsonb

Revision ID: 47f325dd1e1d
Revises: fba9623733ce
Create Date: 2025-09-10 12:43:14.313822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47f325dd1e1d'
down_revision: Union[str, Sequence[str], None] = 'fba9623733ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_results', sa.Column('composite_file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('signal_results', 'after_chart_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_results', sa.Column('after_chart_file_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('signal_results', 'composite_file_ids')
    # ### end Alembic commands ###
