"""make_alert_id_in_signalresult_nullable

Revision ID: 78ad681e813c
Revises: 167114e5ed28
Create Date: 2025-09-04 02:06:57.416937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ad681e813c'
down_revision: Union[str, Sequence[str], None] = '167114e5ed28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signal_results', 'alert_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tokens', 'reply_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'reply_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('signal_results', 'alert_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
