"""add_token_state_and_blacklist

Revision ID: 95cfdbf1bbc1
Revises: bafad5d8b61b
Create Date: 2025-08-31 13:38:41.978205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cfdbf1bbc1'
down_revision: Union[str, Sequence[str], None] = 'bafad5d8b61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklist_token_address'), 'blacklist', ['token_address'], unique=True)
    op.add_column('signal_results', sa.Column('peak_profit_percentage', sa.Float(), nullable=True))
    op.add_column('signal_results', sa.Column('tracking_status', sa.String(), nullable=True))
    op.add_column('signal_results', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_signal_results_status'), table_name='signal_results')
    op.create_index(op.f('ix_signal_results_tracking_status'), 'signal_results', ['tracking_status'], unique=False)
    op.drop_column('signal_results', 'profit_percentage')
    op.drop_column('signal_results', 'status')
    op.add_column('tokens', sa.Column('state', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('last_signal_price', sa.Float(), nullable=True))
    op.add_column('tokens', sa.Column('last_state_change', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tokens_state'), 'tokens', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_state'), table_name='tokens')
    op.drop_column('tokens', 'last_state_change')
    op.drop_column('tokens', 'last_signal_price')
    op.drop_column('tokens', 'state')
    op.add_column('signal_results', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signal_results', sa.Column('profit_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_signal_results_tracking_status'), table_name='signal_results')
    op.create_index(op.f('ix_signal_results_status'), 'signal_results', ['status'], unique=False)
    op.drop_column('signal_results', 'closed_at')
    op.drop_column('signal_results', 'tracking_status')
    op.drop_column('signal_results', 'peak_profit_percentage')
    op.drop_index(op.f('ix_blacklist_token_address'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
