"""Add FibonacciState table

Revision ID: b8d05679340c
Revises: b67100adf532
Create Date: 2025-08-28 00:40:00.547254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d05679340c'
down_revision: Union[str, Sequence[str], None] = 'b67100adf532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fibonacci_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('high_point', sa.Float(), nullable=False),
    sa.Column('low_point', sa.Float(), nullable=False),
    sa.Column('target1_price', sa.Float(), nullable=True),
    sa.Column('target2_price', sa.Float(), nullable=True),
    sa.Column('target3_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_address', 'timeframe', name='_token_timeframe_uc')
    )
    op.create_index(op.f('ix_fibonacci_state_token_address'), 'fibonacci_state', ['token_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fibonacci_state_token_address'), table_name='fibonacci_state')
    op.drop_table('fibonacci_state')
    # ### end Alembic commands ###
